//----------------------------------------------------------------------------------
//! NONEGenerateTumor module definitions.
/*!
// \file    GenerateTumor.script
// \author  LL
*/
//----------------------------------------------------------------------------------


Window {
  Category {
    Box "Create Artificial Tumor"
    {
      Horizontal 
      {
        Field GenerateTumor {
        }
      }
    }
  }
}
